#running postgresql servic here 

version: '3.9'

services:

  Backend: 
    container_name: Backend
    image: mybackend
    build: 
      context: ./Backend
      dockerfile: Dockerfile 
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://sahil:sahil1122@DB:5432/Yume_DB
    env_file:
      - ./Backend/.env

  DB:
    container_name: Database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: sahil1122
      POSTGRES_DB: Yume_DB
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data: {}